stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nickngch90/ssl-nginx:latest
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
