stages:
- name: Generate Certificate
  steps:
  - runScriptConfig:
      image: ubuntu:18.04
      shellScript: |-
        apt update && apt install -y openssl
        ./self_sign_tls.sh proxy.nick-test.com 127.0.0.1
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: ssl-nginx:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 13.59.136.164:30553
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
      namespace: default
timeout: 60
notification: {}
