stages:
- name: Generate Certificate
  steps:
  - runScriptConfig:
      image: ubuntu:18.04
      shellScript: |-
        apt update && apt install -y openssl
        ./self_sign_tls.sh proxy.nick-test.com 127.0.0.1
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: nickngch90/ssl-nginx:latest
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
